services:
  eve-bot-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: snt-tt-dev
    ports:
      - "8800:8800"
    volumes:
      - .:/app               # Monta el proyecto completo
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
    command: poetry run uvicorn app.infrastructure.api.main:app --host 0.0.0.0 --port 8800 --reload

    restart: always

